server:
  port: 8100
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://192.168.31.223:3306/gulimall_sms
    driver-class-name: com.mysql.cj.jdbc.Driver
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.31.223:8848
  application:
    name: gulimall-coupon
mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml